---
- name: Update APT for RaspberryPi
  hosts: raspberrypi
  remote_user: pi
  tasks:
    - name: update
      apt: update_cache=no
      become: true

    - name: upgrade
      apt: upgrade=yes
      become: true

    - name: install list of packages
      apt: name={{item}} state=installed
      with_items:
           - avahi-daemon
