---
- name: update
  apt: update_cache=no

- name: upgrade
  apt: upgrade=yes

- name: install list of packages
  apt:
    pkg:
      - avahi-daemon
    state: present
  notify:
    - restart avahi-daemon