---
- name: update apt-get
  apt: update_cache=no
  register: apt_get_update
  when: apt_get_update is undefined

- name: upgrade apt-get
  apt: upgrade=yes  
  register: apt_get_upgrade
  when: apt_get_upgrade is undefined

- name: install apt debug
  ansible.builtin.debug:
    msg: "apt-get install {{ item }}"
  with_items: "{{ packages }}"
  
- name: install apt {{ packages }}
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present