---
- name: Update Apt-Get
  apt: update_cache=no

- name: Upgrade Apt-Get
  apt: upgrade=yes  

- name: install apt debug
  ansible.builtin.debug:
    msg: "apt-get install {{ item }}"
  with_items: "{{ packages }}"
  
- name: install apt
  ansible.builtin.apt:
    name: "{{  packages  }}"
    state: present